# Project information
site_name: Gameyfin
site_url: https://gameyfin.org
site_author: grimsi
site_description: Documentation for Gameyfin v2, your video game manager.

# Repository
repo_name: gameyfin
repo_url: https://github.com/gameyfin/gameyfin

# Copyright
copyright: Copyright &copy; 2022 - <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/grimsi">grimsi</a> and <a href="https://github.com/gameyfin/gameyfin/graphs/contributors">contributors</a>

# Configuration
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    code: JetBrains Mono
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select

# Plugins
plugins:
  - search
  - glightbox

# Additional configuration
# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gameyfin
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/grimsi
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/gameyfin

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html

# Navigation
nav:
  - "Home":
    - index.md
  - "Installation":
    - installation/index.md
    - installation/migration-from-v1.md
    - installation/docker.md
    - installation/getting-started.md
  - "Configuration":
    - configuration/index.md
    - configuration/libraries.md
    - configuration/users.md
    - configuration/sso.md
    - configuration/messages.md
    - configuration/plugins.md
    - configuration/logs.md
  - "Plugins":
    - plugins/index.md
    - plugins/security.md
    - plugins/info-for-devs.md
    - plugins/tutorial.md